import { Client, Property, Lead, Activity, User, DashboardStats } from '../types';

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    firstName: 'Johan',
    lastName: 'Andersson',
    email: 'johan.andersson@realpro.se',
    role: 'admin',
    avatar: '/avatars/johan.jpg',
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-01'),
  },
  {
    id: '2',
    firstName: 'Emma',
    lastName: 'Lindberg',
    email: 'emma.lindberg@realpro.se',
    role: 'agent',
    avatar: '/avatars/emma.jpg',
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-01-15'),
  },
];

// Mock Clients
export const mockClients: Client[] = [
  {
    id: '1',
    firstName: 'Anders',
    lastName: 'Johansson',
    email: 'anders.johansson@gmail.com',
    phone: '070-123-4567',
    address: 'Sveavägen 45',
    city: 'Stockholm',
    postalCode: '11334',
    notes: 'Looking for a 3-bedroom apartment in Södermalm',
    type: 'buyer',
    createdAt: new Date('2023-02-10'),
    updatedAt: new Date('2023-02-10'),
  },
  {
    id: '2',
    firstName: 'Maria',
    lastName: 'Eriksson',
    email: 'maria.eriksson@outlook.com',
    phone: '073-987-6543',
    address: 'Kungsgatan 12',
    city: 'Stockholm',
    postalCode: '11122',
    notes: 'Selling her apartment to move to a larger house',
    type: 'seller',
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2023-02-15'),
  },
  {
    id: '3',
    firstName: 'Erik',
    lastName: 'Lindgren',
    email: 'erik.lindgren@hotmail.com',
    phone: '076-555-4321',
    address: 'Odengatan 78',
    city: 'Stockholm',
    postalCode: '11322',
    notes: 'Looking to both sell current apartment and buy a house',
    type: 'both',
    createdAt: new Date('2023-03-01'),
    updatedAt: new Date('2023-03-01'),
  },
  {
    id: '4',
    firstName: 'Lena',
    lastName: 'Karlsson',
    email: 'lena.karlsson@gmail.com',
    phone: '070-222-3333',
    address: 'Götgatan 34',
    city: 'Stockholm',
    postalCode: '11826',
    type: 'buyer',
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2023-03-10'),
  },
  {
    id: '5',
    firstName: 'Karl',
    lastName: 'Nilsson',
    email: 'karl.nilsson@gmail.com',
    phone: '073-444-5555',
    address: 'Birger Jarlsgatan 22',
    city: 'Stockholm',
    postalCode: '11434',
    type: 'seller',
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2023-03-15'),
  },
];

// Mock Properties
export const mockProperties: Property[] = [
  {
    id: '1',
    address: 'Hornsgatan 45',
    city: 'Stockholm',
    postalCode: '11728',
    price: 4950000,
    size: 72,
    rooms: 3,
    description: 'Beautiful 3-room apartment in the heart of Södermalm with a balcony and view of Riddarfjärden.',
    status: 'available',
    type: 'apartment',
    images: ['/properties/dashboard-property-1.jpg'],
    ownerId: '2',
    agentId: '2',
    createdAt: new Date('2023-02-20'),
    updatedAt: new Date('2023-02-20'),
    listedAt: new Date('2023-02-25'),
  },
  {
    id: '2',
    address: 'Valhallavägen 128',
    city: 'Stockholm',
    postalCode: '11522',
    price: 7200000,
    size: 110,
    rooms: 4,
    description: 'Spacious 4-room apartment near KTH with newly renovated kitchen and bathroom.',
    status: 'pending',
    type: 'apartment',
    images: ['/properties/dashboard-property-2.jpg'],
    ownerId: '5',
    agentId: '1',
    createdAt: new Date('2023-03-05'),
    updatedAt: new Date('2023-03-05'),
    listedAt: new Date('2023-03-10'),
  },
  {
    id: '3',
    address: 'Norr Mälarstrand 84',
    city: 'Stockholm',
    postalCode: '11220',
    price: 12500000,
    size: 155,
    rooms: 5,
    description: 'Luxurious 5-room apartment with panoramic views of Lake Mälaren and the City Hall.',
    status: 'available',
    type: 'apartment',
    images: ['/properties/dashboard-property-3.jpg'],
    ownerId: '3',
    agentId: '2',
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2023-03-15'),
    listedAt: new Date('2023-03-20'),
  },
  {
    id: '4',
    address: 'Djursholmsvägen 22',
    city: 'Djursholm',
    postalCode: '18257',
    price: 18500000,
    size: 230,
    rooms: 7,
    description: 'Elegant villa from the early 1900s with a large garden and garage for two cars.',
    status: 'available',
    type: 'villa',
    images: ['/properties/dashboard-property-4.jpg'],
    agentId: '1',
    createdAt: new Date('2023-03-25'),
    updatedAt: new Date('2023-03-25'),
    listedAt: new Date('2023-03-30'),
  },
  {
    id: '5',
    address: 'Strandvägen 7',
    city: 'Stockholm',
    postalCode: '11456',
    price: 24900000,
    size: 210,
    rooms: 6,
    description: 'Prestigious apartment on Strandvägen with high ceilings, stucco, and a fireplace.',
    status: 'sold',
    type: 'apartment',
    images: ['/properties/dashboard-property-5.jpg'],
    ownerId: '4',
    agentId: '2',
    createdAt: new Date('2023-01-10'),
    updatedAt: new Date('2023-01-10'),
    listedAt: new Date('2023-01-15'),
    soldAt: new Date('2023-02-28'),
  },
  {
    id: '6',
    address: 'Götgatan 118',
    city: 'Stockholm',
    postalCode: '11862',
    price: 5850000,
    size: 85,
    rooms: 3,
    description: 'Modern 3-room apartment in SoFo with open floor plan and newly renovated kitchen. South-facing balcony.',
    status: 'available',
    type: 'apartment',
    images: ['/properties/dashboard-property-6.jpg'],
    ownerId: '1',
    agentId: '2',
    createdAt: new Date('2023-04-05'),
    updatedAt: new Date('2023-04-05'),
    listedAt: new Date('2023-04-10'),
  },
];

// Mock Leads
export const mockLeads: Lead[] = [
  {
    id: '1',
    firstName: 'Gustav',
    lastName: 'Svensson',
    email: 'gustav.svensson@gmail.com',
    phone: '070-111-2222',
    source: 'website',
    status: 'new',
    notes: 'Interested in properties in Vasastan',
    assignedTo: '2',
    createdAt: new Date('2023-03-28'),
    updatedAt: new Date('2023-03-28'),
  },
  {
    id: '2',
    firstName: 'Sofia',
    lastName: 'Bergström',
    email: 'sofia.bergstrom@hotmail.com',
    phone: '073-333-4444',
    source: 'referral',
    status: 'contacted',
    notes: 'Looking for a summer house in the archipelago',
    assignedTo: '1',
    createdAt: new Date('2023-03-25'),
    updatedAt: new Date('2023-03-26'),
    lastContactedAt: new Date('2023-03-26'),
  },
  {
    id: '3',
    firstName: 'Mikael',
    lastName: 'Öberg',
    email: 'mikael.oberg@gmail.com',
    phone: '076-777-8888',
    source: 'social',
    status: 'qualified',
    notes: 'Interested in investment properties',
    assignedTo: '2',
    createdAt: new Date('2023-03-20'),
    updatedAt: new Date('2023-03-22'),
    lastContactedAt: new Date('2023-03-22'),
  },
  {
    id: '4',
    firstName: 'Anna',
    lastName: 'Holm',
    email: 'anna.holm@outlook.com',
    phone: '070-555-6666',
    source: 'event',
    status: 'proposal',
    notes: 'Looking for a 2-bedroom apartment in Kungsholmen',
    assignedTo: '1',
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2023-03-18'),
    lastContactedAt: new Date('2023-03-18'),
  },
  {
    id: '5',
    firstName: 'Peter',
    lastName: 'Lundqvist',
    email: 'peter.lundqvist@gmail.com',
    phone: '073-999-0000',
    source: 'website',
    status: 'negotiation',
    notes: 'Interested in property ID 3',
    assignedTo: '2',
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2023-03-17'),
    lastContactedAt: new Date('2023-03-17'),
  },
];

// Mock Activities
export const mockActivities: Activity[] = [
  {
    id: '1',
    type: 'call',
    title: 'Initial call with Maria Eriksson',
    description: 'Discussed selling her apartment and her requirements for a new home',
    date: new Date('2023-02-15'),
    completed: true,
    clientId: '2',
    createdAt: new Date('2023-02-14'),
    updatedAt: new Date('2023-02-15'),
  },
  {
    id: '2',
    type: 'meeting',
    title: 'Property valuation at Kungsgatan 12',
    description: 'Meeting with Maria to evaluate her apartment',
    date: new Date('2023-02-18'),
    completed: true,
    clientId: '2',
    propertyId: '1',
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2023-02-18'),
  },
  {
    id: '3',
    type: 'email',
    title: 'Send property listings to Anders',
    description: 'Email Anders with 5 potential apartments in Södermalm',
    date: new Date('2023-02-20'),
    completed: true,
    clientId: '1',
    createdAt: new Date('2023-02-19'),
    updatedAt: new Date('2023-02-20'),
  },
  {
    id: '4',
    type: 'viewing',
    title: 'Property viewing at Hornsgatan 45',
    description: 'Showing the apartment to potential buyers',
    date: new Date('2023-03-05'),
    completed: true,
    propertyId: '1',
    createdAt: new Date('2023-02-25'),
    updatedAt: new Date('2023-03-05'),
  },
  {
    id: '5',
    type: 'offer',
    title: 'Offer on Valhallavägen 128',
    description: 'Received an offer from Anders Johansson',
    date: new Date('2023-03-15'),
    completed: true,
    clientId: '1',
    propertyId: '2',
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2023-03-15'),
  },
  {
    id: '6',
    type: 'meeting',
    title: 'Contract signing for Valhallavägen 128',
    description: 'Meeting with buyer and seller to sign the contract',
    date: new Date(new Date().getTime() + 2 * 24 * 60 * 60 * 1000), // 2 days from now
    completed: false,
    clientId: '1',
    propertyId: '2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    type: 'call',
    title: 'Follow-up with Sofia Bergström',
    description: 'Call to discuss her requirements for a summer house',
    date: new Date(new Date().getTime() + 1 * 24 * 60 * 60 * 1000), // 1 day from now
    completed: false,
    leadId: '2',
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

// Mock Dashboard Stats
export const mockDashboardStats: DashboardStats = {
  totalClients: 128,
  totalProperties: 87,
  totalLeads: 243,
  propertiesSold: 42,
  revenueGenerated: 32750000, // 32.75M SEK
  activeListings: 35,
  pendingDeals: 10,
  newLeadsThisMonth: 28,
}; 